---
image: img-mvipwe0y
prepare:
- mkdir -p ~/.ssh
- cp test/ssh/id_dsa ~/.ssh/
- echo >> ~/.ssh/authorized_keys
- cat test/ssh/authorized_keys >> ~/.ssh/authorized_keys
- chmod 700 ~/.ssh
- chmod 600 ~/.ssh/*
functional_test:
- "./rebar compile ct"
