language: erlang
before_script:
    - mkdir -p ~/.ssh
    - cp test/ssh/id_dsa ~/.ssh/
    - cat test/ssh/authorized_keys >> ~/.ssh/authorized_keys
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/*
    - ssh -oStrictHostKeyChecking=no localhost 'date'
script:
    - ./rebar compile ct
otp_release:
    - R16B
